Repository sainiharit/2.0.github.io, pull requests merged in 2020-10, with the labels that each got.

#10 Update _contact.scss
  assets/scss/_contact.scss
Labels: good first issue

#9 Update jquery-min.js
  assets/js/jquery-min.js
Labels: good first issue

#8 Update main.css
  assets/css/main.css
Labels: bug

#6 Update Index.html
  index.html
Labels: good first issue

#22 Update main.js
  assets/js/main.js
Labels: hacktoberfest-accepted

#21 Update _carousel.scss
  assets/scss/_carousel.scss
Labels: hacktoberfest-accepted

#20 Update form-process.php
  assets/php/form-process.php
Labels: hacktoberfest-accepted

#19 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted
